<!DOCTYPE html >
< html >
< cabeçalho >
  < meta  name =" description " content =" Pacman animado usando CSS puro " >
  < meta  charset =" utf-8 " >
  < meta  name =" viewport " content =" width=device-width " >
  <title> Pacman animado - CSS puro </title>
  < estilo >
    corpo {
      altura : 100 % ;
      fundo : branco;
    }

    . centro {
      exibição : flexível;
      justificar-conteúdo : centralizado;
      alinhar-itens : centro;
    }

    . círculo {
      raio-da-borda :  50 % ;
    }

    . pacman {
      largura : 100 px ;
      altura : 100 px ;
      fundo : azul;
      overflow : oculto;
    }

    . olho {
      largura : 15 px ;
      altura : 15 px ;
      fundo : branco;
      transformar :  traduzirX ( 10 px ) traduzirY ( -30 px )
    }

    . boca {
      animação : comer 0,3 s alternado infinito;
      função-de-temporização-da-animação : linear;
      posição : absoluta;
      largura : 100 px ;
      altura : 0 ;

      borda superior : 50 px sólida transparente;
      borda inferior : 50 px sólida transparente;
      borda-direita : 100 px sólida branca;
    }

    @keyframes comer {
      de {
        borda superior : 60 px sólida transparente;
        borda inferior : 60 px sólida transparente;
      }

      para {
        borda superior : 0 sólida transparente;
        borda-inferior : 0 sólida transparente;
      }
    }
  </ estilo >
</head>​​
< corpo >
    < div  class =" pacman circle center " >
      < div  class = " eye circle " > </div>
      < div  class = " mouth circle " > </div>
    </div>​​
</body>​​
</ html >
